### ISSUE TITLE
Исходники

### ISSUE THREAD

**Issue by dimonpanik** [dpcwee/abot#4]
Может откроете исходный код?

**Comment by lacoste-sochi** [comment]
Конечно...А то чего только авторов вшит механизм проверки на реф код, я тоже свой хочу =)))))))))))))))

**Comment by dimonpanik** [comment]
> Конечно...А то чего только авторов вшит механизм проверки на реф код, я тоже свой хочу =)))))))))))))))

так там же только проверка на реф, смысл?)))
если бот норм, то люди монетой помогут и кодом))

**Comment by lacoste-sochi** [comment]
> > Конечно...А то чего только авторов вшит механизм проверки на реф код, я тоже свой хочу =)))))))))))))))
> 
> так там же только проверка на реф, смысл?)))
> если бот норм, то люди монетой помогут и кодом))

Вот свой напиши))) Тебе помогут... 

А если серьезно, стырят наработки и появятся 1000 коммерческих проектов.

1. По api не вариант вывести деньги с аккаунта, если конечно же по дефолту галочку не включешь.
2. Разработчики зарабатывают - если ты зарабатываешь. 

Вопрос, зачем Вам исходный код? )

**Comment by dimonpanik** [comment]
> 1. По api не вариант вывести деньги с аккаунта, если конечно же по дефолту галочку не включешь.
ахахха, смешно)))
а как же безобъемная монета?)))
 
> Вопрос, зачем Вам исходный код? )

К примеру соседний x-bot сливал апи ключи себе на сервер, но после раскрытия исходного кода удалил данную функцию.
Предполагаю в данном аналогичном боте тоже есть отсылка ключей на сервер))

**Comment by mitagmio** [comment]
Если учесть что у ботов один корень, то конечно это возможно. Ветка xBot очистилась от этого рудимента

**Comment by mitagmio** [comment]
> Может откроете исходный код?

Если не сложно, напишите мне в телеграмм @mitagmio Хочу с вами проконсультироваться

**Comment by dpcwee** [comment]
> > 1. По api не вариант вывести деньги с аккаунта, если конечно же по дефолту галочку не включешь.
> 
> ахахха, смешно)))
> а как же без объемная монета?)))
> 
> > Вопрос, зачем Вам исходный код? )
> 
> К примеру соседний x-bot сливал апи ключи себе на сервер, но после раскрытия исходного кода удалил данную функцию.
> Предполагаю в данном аналогичном боте тоже есть отсылка ключей на сервер))

Ключи не отсылаются на сервер. Из приватной информации на сервере не хранится вообще ничего, только реф id, bep20 реферальный адрес и идентификатор аккаунта.
