### ISSUE TITLE
bybit

### ISSUE THREAD

**Issue by Noname400** [dpcwee/abot#6]
Возможно ли реализация для торговли на bybit.
c бинансом щас реальные сложности.

**Comment by dpcwee** [comment]
> Возможно ли реализация для торговли на bybit. c бинансом щас реальные сложности.

Хочу после нового года начать переписывать бота под bybit, поэтому да, с большой уверенностью бот попозже под неё будет.

**Comment by Noname400** [comment]
Супер очень ждем

**Comment by WorkGroupSol** [comment]
с наступившим!
все ли у разраба в силе по BYBIT
очень интересна система торговли.
