### ISSUE TITLE
BYBIT

### ISSUE THREAD

**Issue by WorkGroupSol** [dpcwee/abot#7]
все ли в силе по реализации вашего кода для BYBIT
очень интересно и хочется начать работу

**Comment by dpcwee** [comment]
> все ли в силе по реализации вашего кода для BYBIT очень интересно и хочется начать работу

Пока что даже не приступали и вряд ли приступим, сейчас занимаемся другими проектами и миграция на байбит больше не в планах:( Будем поддерживать версию для Binance.
